---
title: Teevio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
social:
  twitter: twitter.com/teevio
  instagram: instagram.com/teevio
exclude:
- README.md
- Gemfile
- Gemfile.lock
description: |-
  Stephen Hallgren (aka. Teevio) has been living and breathing all things related to the internet for as long as he can remember.

  Teevio is Partner and CTO at Wayward Wild, a digital product studio helping content creators, podcasts, and publications stay true to their DNA. He is currently focusing his time and talent on the future of podcasting through Wayward Wild’s flagship product, Simplecast.

  In the not so distant past he has worked with everyone from 3D design pioneer Autodesk to Nasty Gal, Dictionary.com and Virb.

  Teevio currently lives in the great and grandiose city of Albany, NY [sarcasm intended] with his wife, 4 children and Bernese Mountain Dog. Aside from programming, he enjoys long walks on the beach, reading, playing guitar, taking photos, and hanging out with his family.

  If you’re ever in town, stop by and say “Hi.”
baseurl: 
url: 
font: 
font_style: 
markdown: kramdown
