---
title: Teevio
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
social:
  twitter: twitter.com/teevio
  instagram: instagram.com/teevio
  adventure: adventure.teev.io
exclude:
- README.md
- Gemfile
- Gemfile.lock
description: "Stephen Hallgren (aka. Teevio) has been living and breathing all things
  related to the internet for as long as he can remember.\n\nTeevio is CTO (Chief
  Technology of Officer) of Audios Ventures, the home of [Simplecast](https://simplecast.com);
  a podcasting and analytics platform empowering audio creators with the tools they
  need to share their stories, evolve their craft, and connect with a world of listeners.\n\nIn
  the not so distant past he has worked with everyone from 3D design pioneer Autodesk
  to Nasty Gal, Dictionary.com and Virb. \n\nTeevio currently lives in the great and
  grandiose city of Albany, NY [sarcasm intended] with his wife, 4 children and Bernese
  Mountain Dog. Aside from programming, he enjoys long walks on the beach, reading,
  playing guitar, taking photos, and hanging out with his family.\n\nIf you’re ever
  in town, stop by and say “Hi.”"
baseurl: 
url: 
font: 
font_style: 
markdown: kramdown
